server:
  port: 7070

jwt:
  secret: ABCDEFGHIJKDKJFKLDJFKLSJDKLFJSKLDJFKLSJDFKLJSDKLFJKLDKLFJSKLDJFLKSJDFJSKLDJFKLJSDLKFJKLSD
  access_token.expire : 100000
  refresh_token.expire : 10000000
spring:
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1

