server:
  port: 18080

spring.cloud.gateway:
  routes:
    - id: podo
      uri: http://localhost:8080
      predicates:
        - Path=/**
#    - id : naver
#      uri : https://www.naver.com
#      predicates:
#        - Path=/naver/**
