server:
  port: 18080

jwt:
  secret: ABCDEFGHIJKDKJFKLDJFKLSJDKLFJSKLDJFKLSJDFKLJSDKLFJKLDKLFJSKLDJFLKSJDFJSKLDJFKLJSDLKFJKLSD

spring:
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1

